name: p2
version: 0.5.2
description:
  A Dart port for P2.js 2D physics library.
author: playif <playif@gmail.com>
homepage: https://github.com/playif/play_p2

dev_dependencies:
  browser: any
  play_pixi: any
  datgui: any